### ISSUE TITLE
can not start rails with i18n_language_select

### ISSUE THREAD

**Issue by pejuko** [Sitata/i18n_language_select#1]
If I put

``` ruby
gem 'i18n_language_select'
```

into Gemfile I get error

```
bin/rails:6: warning: already initialized constant APP_PATH
bin/rails:6: warning: previous definition of APP_PATH was here
```

and rails wont start

**Comment by pejuko** [comment]
I'm using rails 4.2

**Comment by pejuko** [comment]
with rackup I got

```
Uncaught exception: cannot load such file -- threach
    /home/devel/.rvm/gems/ruby-2.2.0/gems/i18n_language_select-0.0.1/lib/i18n_language_select/import.rb:4:in `require'
    /home/devel/.rvm/gems/ruby-2.2.0/gems/i18n_language_select-0.0.1/lib/i18n_language_select/import.rb:4:in `<top (required)>'
    /home/devel/.rvm/gems/ruby-2.2.0/gems/i18n_language_select-0.0.1/lib/i18n_language_select.rb:5:in `require'
    /home/devel/.rvm/gems/ruby-2.2.0/gems/i18n_language_select-0.0.1/lib/i18n_language_select.rb:5:in `<top (required)>'
```

so if I add

``` ruby
gem 'threach'
```

into Gemfile it works
